C=g++ -Wall -g
OFLAGS=`pkg-config --libs --cflags opencv`


opencv-cam-phototaker: opencv-cam-phototaker.cpp
	$(C) opencv-cam-phototaker.cpp $(OFLAGS) -o opencv-cam-phototaker

opencv-cam-phototaker-ng: opencv-cam-phototaker-ng.cpp
	$(C) opencv-cam-phototaker-ng.cpp $(OFLAGS) -o opencv-cam-phototaker-ng

